[package]
name = "boid_playground"
version = "0.1.0"
edition = "2024"

[dependencies]
boid_simulation = { path = "../boid_simulation" }
macroquad = { version = "0.4", default-features = false }
egui-macroquad = "0.17"
